=== buha/flute-thesis/xml/woodwind.dtd
<!-- woodwind.dtd -->
<!-- Paul Dickens - February 2007 -->
<!-- Data Type Definition for a woodwind -->
<!ELEMENT woodwind ((embouchurehole, upstream)?, downstream)>
<!ATTLIST woodwind description CDATA #IMPLIED>
<!ELEMENT embouchurehole (radiusin, radiusout, length, boreradius)>
<!ELEMENT upstream (bore+)>
<!ATTLIST upstream flange CDATA #REQUIRED>
<!ELEMENT downstream (bore, (hole | bore)*)>
<!ATTLIST downstream flange CDATA #REQUIRED>
<!ELEMENT bore (radius1, radius2, length)>
<!ELEMENT hole (radius, length, boreradius, key?)>
<!ATTLIST hole name CDATA #IMPLIED>
<!ELEMENT key (radius, holeradius, height, thickness, wallThickness,
chimneyHeight)>
<!ELEMENT radius (#PCDATA)>
<!ELEMENT radiusin (#PCDATA)>
<!ELEMENT radiusout (#PCDATA)>
<!ELEMENT radius1 (#PCDATA)>
<!ELEMENT radius2 (#PCDATA)>
<!ELEMENT boreradius (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT holeradius (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT thickness (#PCDATA)>
<!ELEMENT wallThickness (#PCDATA)>
<!ELEMENT chimneyHeight (#PCDATA)>

=== buha/flute-thesis/xml/ModernFlute.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE woodwind SYSTEM "woodwind.dtd">
<woodwind description="Pearl flute PF-661 open hole">
  <embouchurehole>
    <radiusin>6.4</radiusin>
    <radiusout>5.7</radiusout>
    <length>4.4</length>
    <boreradius>8.533587786259544</boreradius>
  </embouchurehole>
  <upstream flange="-1.0">
    <bore>
      <radius1>8.533587786259544</radius1>
      <radius2>8.4</radius2>
      <length>17.5</length>
    </bore>
  </upstream>
  <downstream flange="0.1">
    <bore>
      <radius1>8.533587786259544</radius1>
      <radius2>9.4</radius2>
      <length>113.5</length>
    </bore>
    <bore>
      <radius1>9.4</radius1>
      <radius2>9.4</radius2>
      <length>37.0</length>
    </bore>
    <bore>
      <radius1>9.9</radius1>
      <radius2>9.9</radius2>
      <length>4.0</length>
    </bore>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>46.2</length>
    </bore>
    <hole name="Tr1">
      <radius>3.7</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>6.5</radius>
        <holeradius>0.0</holeradius>
        <height>1.6</height>
        <thickness>3.6</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>17.3</length>
    </bore>
    <hole name="Tr2">
      <radius>3.9</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>6.5</radius>
        <holeradius>0.0</holeradius>
        <height>1.6</height>
        <thickness>3.6</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>16.4</length>
    </bore>
    <hole name="C#">
      <radius>3.5</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>6.5</radius>
        <holeradius>0.0</holeradius>
        <height>1.9</height>
        <thickness>3.6</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>32.5</length>
    </bore>
    <hole name="C">
      <radius>6.6</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>9.5</radius>
        <holeradius>0.0</holeradius>
        <height>2.6</height>
        <thickness>3.6</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>19.2</length>
    </bore>
    <hole name="B">
      <radius>6.6</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>9.5</radius>
        <holeradius>0.0</holeradius>
        <height>2.2</height>
        <thickness>4.0</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>21.0</length>
    </bore>
    <hole name="A#">
      <radius>6.6</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>9.5</radius>
        <holeradius>3.4</holeradius>
        <height>2.5</height>
        <thickness>4.2</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>23.2</length>
    </bore>
    <hole name="A">
      <radius>6.6</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>9.5</radius>
        <holeradius>3.4</holeradius>
        <height>2.4</height>
        <thickness>4.2</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>21.7</length>
    </bore>
    <hole name="G#">
      <radius>6.7</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>9.5</radius>
        <holeradius>0.0</holeradius>
        <height>2.4</height>
        <thickness>4.0</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>0.5</length>
    </bore>
    <hole name="G# dup.">
      <radius>6.7</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>9.5</radius>
        <holeradius>0.0</holeradius>
        <height>2.5</height>
        <thickness>4.0</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>24.4</length>
    </bore>
    <hole name="G">
      <radius>7.1</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>9.5</radius>
        <holeradius>0.0</holeradius>
        <height>2.1</height>
        <thickness>4.0</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>25.7</length>
    </bore>
    <hole name="F#">
      <radius>7.1</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>9.5</radius>
        <holeradius>3.4</holeradius>
        <height>2.3</height>
        <thickness>4.2</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>27.3</length>
    </bore>
    <hole name="F">
      <radius>7.1</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>9.5</radius>
        <holeradius>3.4</holeradius>
        <height>2.5</height>
        <thickness>4.2</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>28.8</length>
    </bore>
    <hole name="E">
      <radius>7.1</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>9.5</radius>
        <holeradius>3.4</holeradius>
        <height>2.4</height>
        <thickness>4.2</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>20.7</length>
    </bore>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>10.9</length>
    </bore>
    <hole name="D#">
      <radius>7.7</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>10.3</radius>
        <holeradius>0.0</holeradius>
        <height>2.8</height>
        <thickness>4.0</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>34.0</length>
    </bore>
    <hole name="D">
      <radius>7.7</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>10.3</radius>
        <holeradius>0.0</holeradius>
        <height>2.8</height>
        <thickness>4.0</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>33.0</length>
    </bore>
    <hole name="C#">
      <radius>7.7</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>10.3</radius>
        <holeradius>0.0</holeradius>
        <height>2.8</height>
        <thickness>4.0</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <!-- Use this code for C foot -->
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>43.1</length>
    </bore>
    <!-- end of code for C foot -->
    <!-- Use this code for B foot -->
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>35.0</length>
    </bore>
    <hole name="C">
      <radius>7.7</radius>
      <length>1.9</length>
      <boreradius>9.5</boreradius>
      <key>
        <radius>10.3</radius>
        <holeradius>0.0</holeradius>
        <height>2.8</height>
        <thickness>4.0</thickness>
        <wallThickness>1.0</wallThickness>
        <chimneyHeight>1.5</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>41.0</length>
    </bore>
    <!-- end of code for B foot -->
  </downstream>
</woodwind>

=== buha/flute-thesis/xml/KavalSib.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE woodwind SYSTEM "woodwind.dtd">
<woodwind description="Turkish 8-hole kaval">
  <downstream flange="0.625p">
   <bore>
     <radius1>8</radius1>
     <radius2>8</radius2>
     <length>345.5</length>
    </bore>
    <hole name="Backhole">
      <radius>4.25</radius>
      <length>1.5</length>
      <boreradius>8</boreradius>
    </hole>
    <bore>
     <radius1>8</radius1>
     <radius2>8</radius2>
     <length>44.5</length>
    </bore>
    <hole name="Hole7">
      <radius>2.9</radius>
      <length>1.5</length>
      <boreradius>8</boreradius>
    </hole>
    <bore>
     <radius1>8</radius1>
     <radius2>8</radius2>
     <length>33</length>
    </bore>
    <hole name="Hole6">
      <radius>4.25</radius>
      <length>1.5</length>
      <boreradius>8</boreradius>
    </hole>
    <bore>
     <radius1>8</radius1>
     <radius2>8</radius2>
     <length>31</length>
    </bore>
    <hole name="Hole5">
      <radius>4.25</radius>
      <length>1.5</length>
      <boreradius>8</boreradius>
    </hole>
    <bore>
     <radius1>8</radius1>
     <radius2>8</radius2>
     <length>32</length>
    </bore>
    <hole name="Hole4">
      <radius>4.25</radius>
      <length>1.5</length>
      <boreradius>8</boreradius>
    </hole>
    <bore>
     <radius1>8</radius1>
     <radius2>8</radius2>
     <length>34.5</length>
    </bore>
    <hole name="H3">
      <radius>4.25</radius>
      <length>1.5</length>
      <boreradius>8</boreradius>
    </hole>
    <bore>
     <radius1>8</radius1>
     <radius2>8</radius2>
     <length>30</length>
    </bore>
    <hole name="H2">
      <radius>4.25</radius>
      <length>1.5</length>
      <boreradius>8</boreradius>
    </hole>
    <bore>
     <radius1>8</radius1>
     <radius2>8</radius2>
     <length>33</length>
    </bore>
    <hole name="H1">
      <radius>4.25</radius>
      <length>1.5</length>
      <boreradius>8</boreradius>
    </hole>
    <bore>
     <radius1>8</radius1>
     <radius2>8</radius2>
     <length>83.5</length>
    </bore>
    <hole name="Tuninghole2">
      <radius>4.25</radius>
      <length>1.5</length>
      <boreradius>8</boreradius>
    </hole>
    <bore>
     <radius1>8</radius1>
     <radius2>8</radius2>
     <length>48</length>
    </bore>
    <hole name="Tuninghole1">
      <radius>8.5</radius>
      <length>1.5</length>
      <boreradius>8</boreradius>
    </hole>
    <bore>
     <radius1>8</radius1>
     <radius2>8</radius2>
     <length>58</length>
    </bore>
  </downstream>
</woodwind>

=== buha/flute-thesis/xml/ClassicalFlute.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE woodwind SYSTEM "woodwind.dtd">
<woodwind description="McGee classical flute">
  <embouchurehole>
    <radiusin>5.7</radiusin>
    <radiusout>5.5</radiusout>
    <length>3.5</length>
    <boreradius>9.5</boreradius>
  </embouchurehole>
  <upstream flange="-1.0">
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>19.0</length>
    </bore>
  </upstream>
  <downstream flange="0.75">
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.5</radius2>
      <length>139.5</length>
    </bore>
    <bore>
      <radius1>10.0</radius1>
      <radius2>10.0</radius2>
      <length>12.8</length>
    </bore>
    <bore>
      <radius1>9.5</radius1>
      <radius2>9.2</radius2>
      <length>2.0</length>
    </bore>
    <bore>
      <radius1>9.2</radius1>
      <radius2>8.6</radius2>
      <length>83.5</length>
    </bore>
    <hole name="L1">
      <radius>4.0</radius>
      <length>4.8</length>
      <boreradius>8.6</boreradius>
    </hole>
    <bore>
      <radius1>8.6</radius1>
      <radius2>8.412073490813647</radius2>
      <length>17.9</length>
    </bore>
    <hole name="C">
      <radius>3.2</radius>
      <length>4.5</length>
      <boreradius>8.412073490813647</boreradius>
      <key>
        <radius>6.7</radius>
        <holeradius>0.0</holeradius>
        <height>4.0</height>
        <thickness>4.0</thickness>
        <wallThickness>3.0</wallThickness>
        <chimneyHeight>0.0</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>8.412073490813647</radius1>
      <radius2>8.2</radius2>
      <length>20.2</length>
    </bore>
    <hole name="L2">
      <radius>5.1</radius>
      <length>4.9</length>
      <boreradius>8.2</boreradius>
    </hole>
    <bore>
      <radius1>8.2</radius1>
      <radius2>8.032743362831859</radius2>
      <length>18.9</length>
    </bore>
    <hole name="Bb">
      <radius>3.0</radius>
      <length>4.5</length>
      <boreradius>8.032743362831859</boreradius>
      <key>
        <radius>5.7</radius>
        <holeradius>0.0</holeradius>
        <height>2.0</height>
        <thickness>2.5</thickness>
        <wallThickness>3.0</wallThickness>
        <chimneyHeight>0.0</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>8.032743362831859</radius1>
      <radius2>7.9</radius2>
      <length>15.0</length>
    </bore>
    <hole name="L3">
      <radius>4.0</radius>
      <length>5.0</length>
      <boreradius>7.9</boreradius>
    </hole>
    <bore>
      <radius1>7.9</radius1>
      <radius2>7.665720081135903</radius2>
      <length>23.1</length>
    </bore>
    <hole name="G#">
      <radius>3.0</radius>
      <length>4.5</length>
      <boreradius>7.665720081135903</boreradius>
      <key>
        <radius>6.0</radius>
        <holeradius>0.0</holeradius>
        <height>2.7</height>
        <thickness>3.0</thickness>
        <wallThickness>3.0</wallThickness>
        <chimneyHeight>0.0</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>7.665720081135903</radius1>
      <radius2>7.4</radius2>
      <length>26.2</length>
    </bore>
    <bore>
      <radius1>7.5</radius1>
      <radius2>7.4</radius2>
      <length>8.6</length>
    </bore>
    <hole name="R1">
      <radius>4.8</radius>
      <length>5.1</length>
      <boreradius>7.4</boreradius>
    </hole>
    <bore>
      <radius1>7.4</radius1>
      <radius2>7.1</radius2>
      <length>31.0</length>
    </bore>
    <hole name="R2">
      <radius>5.5</radius>
      <length>5.0</length>
      <boreradius>7.1</boreradius>
    </hole>
    <bore>
      <radius1>7.1</radius1>
      <radius2>6.8</radius2>
      <length>20.4</length>
    </bore>
    <hole name="F">
      <radius>4.0</radius>
      <length>4.5</length>
      <boreradius>6.8</boreradius>
      <key>
        <radius>6.7</radius>
        <holeradius>0.0</holeradius>
        <height>1.9</height>
        <thickness>4.0</thickness>
        <wallThickness>3.0</wallThickness>
        <chimneyHeight>0.0</chimneyHeight>
      </key>
    </hole>
    <bore>
      <radius1>6.8</radius1>
      <radius2>6.8</radius2>
      <length>15.5</length>
    </bore>
    <hole name="R3">
      <radius>3.3</radius>
      <length>5.2</length>
      <boreradius>6.8</boreradius>
    </hole>
    <bore>
      <radius1>6.8</radius1>
      <radius2>6.6</radius2>
      <length>35.4</length>
    </bore>
    <bore>
      <radius1>6.8</radius1>
      <radius2>6.8</radius2>
      <length>52.3</length>
    </bore>
    <hole name="C#">
      <radius>6.5</radius>
      <length>5.1</length>
      <boreradius>6.8</boreradius>
    </hole>
    <bore>
      <radius1>6.8</radius1>
      <radius2>6.7</radius2>
      <length>36.7</length>
    </bore>
    <hole name="C">
      <radius>5.2</radius>
      <length>5.0</length>
      <boreradius>6.7</boreradius>
    </hole>
    <bore>
      <radius1>6.7</radius1>
      <radius2>6.7</radius2>
      <length>39.2</length>
    </bore>
  </downstream>
</woodwind>
